version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasks

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
